[package]
name = "common"
description = "ğŸ™ Â» common utilities for all commands"
publish = false
version.workspace = true
readme.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
regex = "1.10.6"
regex-lite = "0.1.6"
lool = { workspace = true, features = ["cli.stylize", "macros"] }
spinners = "4.1.1"
eyre = { workspace = true }
pico-args = "0.5.0"
